M48
; DRILL file {KiCad 7.0.3} date Mon 10 Jul 2023 12:40:13 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-10T12:40:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X2.6097Y-2.8646
X2.7761Y-2.7094
X4.3106Y-5.5946
X4.5244Y-5.5168
T2
X3.3112Y-5.6078
X3.5628Y-5.6993
T0
M30
